### ISSUE TITLE
Write a getting started guide for an application project team

### ISSUE THREAD

**Issue by psakievich** [sandialabs/spack-manager#632]
Create a getting started guide. Potential outline:

``` yaml
Welcome:
Getting Started:
- Create your spack-manager project
- Create your config contexts
- Create your package repos
- Create your context detection scripts
- Test your project is working
Setup you CI:
- How to use Spack CI to test your project
  - Gitlab
  - Github
Setup a binary cache for your project
- S3, OCI, Filesystem
- Data management strategies
Setup Upstreams
- Data managment
Releasing your software
- Update packages
- Manage your caches
Deploying your software
- Create a src mirror for customers to use
- Create a binary mirror for customers to use
- Create a tarfile
```
